### PR TITLE
Add function for parsing and header file in c++

### PR DESCRIPTION
**Pull request by mihir001**

### CODE REVIEW

**Comment by maruthgoyal** [comment]
Which school is this?

**Comment by mihir001** [comment]
DPS greater noida

**Comment by starrickcrwford** [comment]
Style violations in both files. System header was after the other header, improper spacing and use of braces. All in all, I count 47 violations.

**Comment by maruthgoyal** [comment]
@starrickcrwford is right @mihir001 . Also, there's a severe lack of tests in your code.

**Comment by maruthgoyal** [comment]
Also, you're allocating a character array of size **500,000!!!!** That's not how you use dynamic memory allocation man.

**Pull request closed without merging**
